### ISSUE TITLE
Crash when purging cache

### ISSUE THREAD

**Issue by franziskuskiefer** [wireapp/wire-ios-cryptobox#39]
When filling up the cache with entries we run into a crash.
Repeatedly calling `encryptCaching` in https://github.com/wireapp/wire-ios-cryptobox/blob/develop/WireCryptobox/EncryptionSessionsDirectory.swift#L122 the `n` most recent entries should be stored and old values should get purged if necessary.
When adding a test that actually exercises this it simply crashes in `purgeBaseOnCost with Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`. (See https://github.com/wireapp/wire-ios-cryptobox/compare/franziskus/caching-purge-test for code doing this.)

I suspect that the cache itself (in https://github.com/wireapp/wire-ios-system) is broken.

**Comment by typfel** [comment]
This was already fixed in `wire-ios-system` https://github.com/wireapp/wire-ios-system/pull/52 but the version wasn't bumped in `wire-ios-cryptobox`.

**Comment by franziskuskiefer** [comment]
Nice 👍 
The question is then where's the issue that bumps the version and how do we avoid something like this in future?

**Comment by typfel** [comment]
Since the fix was a patch release it's already included in our app it was just not bumped in all dependencies. We only explicitly bump dependencies on major releases.
